# Generated by Django 5.2.6 on 2025-10-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_movie_genre_movie_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.TextField(blank=True, null=True),
        ),
    ]
